### ISSUE TITLE
Don't working

### ISSUE THREAD

**Issue by qqsob** [TheDiVaZo/MessageOverHead#12]
when writing any message in the chat, it gives an error:
[21:52:20 ERROR]: Could not pass event AsyncPlayerChatEvent to MessageOverHead v2.52
java.lang.RuntimeException: An internal error occured.
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:513) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:525) ~[ProtocolLib.jar:?]
        at thedivazo.utils.Bubble.setMetadata(Bubble.java:93) ~[MessageOverHead-2.52-all.jar:?]
        at thedivazo.utils.Bubble.<init>(Bubble.java:62) ~[MessageOverHead-2.52-all.jar:?]
        at thedivazo.utils.BubbleMessage.<init>(BubbleMessage.java:69) ~[MessageOverHead-2.52-all.jar:?]
        at thedivazo.listener.Listeners.onPlayerChat(Listeners.java:67) ~[MessageOverHead-2.52-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.EventExecutor$$Lambda$5371/0x0000000099679e08.execute(Unknown Source) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-283]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:194) ~[paper-1.18.2.jar:git-Paper-283]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:66) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2223) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2134) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.network.syncher.SynchedEntityData.set(SynchedEntityData.java:141) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[ProtocolLib.jar:?]
        ... 21 more

**Comment by qqsob** [comment]
but no. everything is fine, it was necessary to update ProtocolLIB

**Comment by qqsob** [comment]
thanks to the author

**Comment by TheDiVaZo** [comment]
It works?

**Comment by qqsob** [comment]
Yes!
