### ISSUE TITLE
plugin dont work

### ISSUE THREAD

**Issue by BuchNieZyje** [TheDiVaZo/MessageOverHead#15]
Config generated, i dont touch it
console :

Could not pass event AsyncPlayerChatEvent to MessageOverHead v2.53
java.lang.NumberFormatException: multiple points
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source) ~[?:?]
        at java.lang.Float.parseFloat(Unknown Source) ~[?:?]
        at thedivazo.Main.getVersion(Main.java:83) ~[MessageOverHead-2.53-all.jar:?]
        at thedivazo.utils.ColorString.ofLine(ColorString.java:66) ~[MessageOverHead-2.53-all.jar:?]
        at thedivazo.listener.Listeners.onPlayerChat(Listeners.java:62) ~[MessageOverHead-2.53-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor111.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.EventExecutor$$Lambda$5886/0x0000000002a74d70.execute(Unknown Source) ~[app:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-399]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Paper-399]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Paper-399]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2179) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.chat(CraftPlayer.java:642) ~[patched_1.17.1.jar:git-Paper-399]
        at me.jomi.mimiRPG.Chat.PiszJako.wykonajKomende(PiszJako.java:42) ~[mimiRPG.jar:?]
        at me.jomi.mimiRPG.util.Komenda.onCommand(Komenda.java:133) ~[mimiRPG.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-399]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$11263/0x0000000002171d08.run(Unknown Source) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-399]
        at net.minecraft.server.MinecraftServer$$Lambda$3647/0x0000000091fd61c8.run(Unknown Source) ~[app:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by TheDiVaZo** [comment]
Hi, please, write a name of core and minecraft version

**Comment by TheDiVaZo** [comment]
Plugib has benn fixed!!! Please download last version
