### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by TalentsDX** [TheDiVaZo/MessageOverHead#3]
Server：Purpur-1.16.5（1171）

Log：
[17:23:46 ERROR]: Could not pass event AsyncPlayerChatEvent to MessageOverHead v
2.2
java.lang.IllegalArgumentException: Cannot measure distance between world_nether
 and world
        at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16
.5.jar:git-Purpur-1171]
        at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.5.jar:
git-Purpur-1171]
        at thedivazo.BubbleMessage.sound(BubbleMessage.java:121) ~[?:?]
        at thedivazo.listener.Listeners.onPlayerChat(Listeners.java:57) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
ecutor328.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69
) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
6) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225)
 ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatPr
ocessor.java:107) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:6
5) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.
java:2232) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.jav
a:2147) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.jav
a:2085) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat
.java:43) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~
[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by TheDiVaZo** [comment]
The bug will be fixed in a few hours, it's better to write to the discord, here I don't always follow the mistakes

**Comment by TalentsDX** [comment]
> The bug will be fixed in a few hours, it's better to write to the discord, here I don't always follow the mistakes

ok
