### ISSUE TITLE
strange error that never happened before

### ISSUE THREAD

**Issue by ProdByPengu** [TheDiVaZo/MessageOverHead#35]
```
[14:42:59 ERROR]: Could not pass event AsyncPlayerChatEvent to MessageOverHead v3.3
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructors()" because "com.comphenix.protocol.wrappers.WrappedDataValue.HANDLE_TYPE" is null
        at com.comphenix.protocol.wrappers.WrappedDataValue.newHandle(WrappedDataValue.java:38) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.wrappers.WrappedDataValue.<init>(WrappedDataValue.java:33) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at thedivazo.Bubble.getMetaPacket(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.Bubble.spawn(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.BubbleMessage.show(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.bubblemessagemanager.BubbleMessageManager.showBubble(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.bubblemessagemanager.BubbleMessageManager.lambda$showBubble$0(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at thedivazo.bubblemessagemanager.BubbleMessageManager.showBubble(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.MessageOverHead.createBubbleMessage(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.MessageOverHead.createBubbleMessage(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at thedivazo.listener.chatlistener.DefaultChatListener.onPlayerChat(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor185.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2405) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2590) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:42:59 INFO]: [Not Secure] OWNER ProdByPengu: t
```

**Comment by TheDiVaZo** [comment]
What version of minecraft and lib protocol are you using?

**Comment by ProdByPengu** [comment]
Fixed it, it was my protocollib versoon

**Comment by TheDiVaZo** [comment]
Okay
