### ISSUE TITLE
Error after send message to chat

### ISSUE THREAD

**Issue by koval01** [TheDiVaZo/MessageOverHead#36]
I see this error in logs after send any message to chat
```log
[22:14:51 ERROR]: Could not pass event AsyncPlayerChatEvent to MessageOverHead v3.3
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedDataValue
	at thedivazo.Bubble.getMetaPacket(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.Bubble.spawn(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.BubbleMessage.show(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.bubblemessagemanager.BubbleMessageManager.showBubble(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.bubblemessagemanager.BubbleMessageManager.lambda$showBubble$0(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at thedivazo.bubblemessagemanager.BubbleMessageManager.showBubble(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.MessageOverHead.createBubbleMessage(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.MessageOverHead.createBubbleMessage(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at thedivazo.listener.chatlistener.DefaultChatListener.onPlayerChat(Unknown Source) ~[MessageOverHead-3.3-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor741.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:381) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2496) ~[?:git-Purpur-1858]
	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2681) ~[?:git-Purpur-1858]
	at net.minecraft.server.network.PlayerConnection.lambda$handleChat$18(PlayerConnection.java:2321) ~[?:git-Purpur-1858]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by TheDiVaZo** [comment]
What version of minecraft and protocolLib?

**Comment by koval01** [comment]
[Latest version](https://ci.dmulloy2.net/job/ProtocolLib/606/) for 1.19.2
Most of the plugins we use require the latest version

**Comment by TheDiVaZo** [comment]
Okay, i will fix it on next update
