### ISSUE TITLE
Plugin no work error

### ISSUE THREAD

**Issue by zoi1op** [TheDiVaZo/MessageOverHead#39]
Привет у меня не работает плагин выдает ошибку
```[20:25:43 INFO] [MessageOverHead]: Enabling MessageOverHead v3.4
[20:25:43 INFO] [MessageOverHead]: Starting...
[20:25:43 WARN] [MessageOverHead]: Ошибка обновления настроек плагина! Пожалуйста, проверьте конфиг на наличие опечаток!
[20:25:43 ERROR] [Minecraft]: Error occurred while enabling MessageOverHead v3.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String)" because "<local3>" is null
        at thedivazo.config.ConfigManager.saveSettingsPlugin(Unknown Source) ~[?:?]
        at thedivazo.config.ConfigManager.reloadConfigFile(Unknown Source) ~[?:?]
        at thedivazo.config.ConfigManager.<init>(Unknown Source) ~[?:?]
        at thedivazo.MessageOverHead.onEnable(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.19.2-1.0.2-4a870b30.jar%23164!/:arclight-1.19.2-1.0.2-4a870b30]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.19.2-1.0.2-4a870b30.jar%23164!/:arclight-1.19.2-1.0.2-4a870b30]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.19.2-1.0.2-4a870b30.jar%23164!/:arclight-1.19.2-1.0.2-4a870b30]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServerMixin.java:525) ~[arclight-1.19.2-1.0.2-4a870b30.jar%23164!/:arclight-1.19.2-1.0.2-4a870b30]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServerMixin.java:439) ~[arclight-1.19.2-1.0.2-4a870b30.jar%23164!/:arclight-1.19.2-1.0.2-4a870b30]
        at net.minecraft.server.MinecraftServer.handler$zba000$arclight$enablePlugins(MinecraftServerMixin.java:2194) ~[server-1.19.2-20220805.130853-srg.jar%23171!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:375) ~[server-1.19.2-20220805.130853-srg.jar%23171!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:300) ~[server-1.19.2-20220805.130853-srg.jar%23171!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:165) ~[server-1.19.2-20220805.130853-srg.jar%23171!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2087) ~[server-1.19.2-20220805.130853-srg.jar%23171!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23171!/:?]
        at java.l
ang.Thread.run(Thread.java:833) [?:?]```

**Comment by danir-de** [comment]
There seems to be an issue with the default configuration file that gets generated.
