### ISSUE TITLE
Send a large number of "?" Resulting in an error 

### ISSUE THREAD

**Issue by TalentsDX** [TheDiVaZo/MessageOverHead#9]
Version ：purpur-1.16.5

How this error occurred: Send a lot of "?" 
For Example ： ？？？？？？？？？？？？？？？？？？？？？？？？

log：
[17:50:01 ERROR]: Could not pass event AsyncPlayerChatEvent to MessageOverHead v
2.4
java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 0

????????????????????????
^
        at java.util.regex.Pattern.error(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.sequence(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.expr(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.<init>(Unknown Source) ~[?:?]
        at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
        at java.lang.String.replaceFirst(Unknown Source) ~[?:?]
        at thedivazo.utils.BubbleMessage.<init>(BubbleMessage.java:47) ~[?:?]
        at thedivazo.listener.Listeners.onPlayerChat(Listeners.java:66) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
ecutor401.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69
) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
6) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225)
 ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatPr
ocessor.java:107) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:6
5) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.
java:2232) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.jav
a:2147) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.jav
a:2085) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat
.java:43) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~
[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by TheDiVaZo** [comment]
Fix in update 2.5

**Comment by TheDiVaZo** [comment]
Fixed! Close issues
